# Generated by Django 4.0.2 on 2022-03-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.dish_category'),
        ),
        migrations.AlterField(
            model_name='dish_category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Dish category'),
        ),
        migrations.AlterField(
            model_name='dish_category',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
