# Generated by Django 4.0.2 on 2022-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_category',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
