# Generated by Django 4.0.1 on 2022-02-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220111_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='admin',
        ),
    ]
