# Generated by Django 4.0.2 on 2022-03-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
