# Generated by Django 4.0.2 on 2022-05-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_dish_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_category',
            name='category_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Dish category'),
        ),
    ]
