# Generated by Django 4.0.2 on 2022-02-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_dish_category_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish_category',
            old_name='date',
            new_name='added',
        ),
    ]
