# Generated by Django 4.0.2 on 2022-05-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
