# Generated by Django 4.0.7 on 2022-08-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_table_rotation_table_shape_table_sides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='bookings.room'),
        ),
        migrations.AlterField(
            model_name='table',
            name='x_pos',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='table',
            name='y_pos',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
