# Generated by Django 4.0.7 on 2022-08-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_table_room_alter_table_x_pos_alter_table_y_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='x_pos',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='y_pos',
            new_name='y',
        ),
    ]
